library(MASS)
library(wavethresh)
library(data.table)
library(penGAM)
library(SAM)
library(mgcv)
library(plot.matrix)
library(ismev)
library(faraway)
library(chemometrics)
library(glmnet)

source('functions.R')
source('auxiliary_functions.R')

source('lambdaQUT.sqrtwavethresh.R')
source('lambdaQUT.softwavethresh.R')
source('lambdaQUT.AMlet.R')
source('lambdaQUT.AMlet.Linear.R')
source('lambdaQUT.AMlet.Haar.R')
source('lambdaQUT.AMlet.Haar.Linear.R')
source('lambdaQUT.sqrtAMlet.R')
source('lambdaQUT.sqrtAMlet.Linear.R')
source('lambdaQUT.sqrtAMlet.Haar.R')
source('lambdaQUT.sqrtAMlet.Haar.Linear.R')

source('closedformIdentity.R')
source('linearsolution.R')
source('sqrtLinear.R')

source('sqrtwavethresh.R')
source('softwavethresh.R')

source('sqrtAMlet.R')
source('sqrtAMlet.Haar.R')
source('sqrtAMlet.Linear.R')
source('sqrtAMlet.Haar.Linear.R')
source('AMlet.Universal.Mad.R')
source('AMlet.QUT.oracle.R')
source('AMlet.QUT.Mad.R')
source('AMlet.QUT.Mad.Haar.R')
source('AMlet.QUT.Mad.Linear.R')
source('AMlet.QUT.Mad.Haar.Linear.R')

source('predict.sqrtwavethresh.R')
source('predict.softwavethresh.R')
source('predict.sqrtAMlet.R')
source('predict.AMlet.R')


source('HAM.R')
source('SRAMlet.R')
source('AMlet.R')


